Sachindrck/hactoberfest_contribution_2022

Python/Simple_calculator.py
This pull request solves issue #4 .
=> Added Calculator code

Python/multiplicative_chiper.py
Hi, I'm adding simple cryptography method called multiplicative chiper
=> adding multiplicative_chiper

Python/Armstrong_number.py, Python/Python Program to Check Armstrong Number.txt
hey @Sachindrck I have submitted a code and algorithm for How to check a number is Armstrong or not ?
=> armstrong number

Python/hello_world.py
=> Created Hello World

C++/Search in Rotated Sorted Array.cpp
=> Created Search in Rotated Sorted Array.cpp

C++/hello_world.cpp
Added cpp program for hello world
closes #17
=> Hello_world_program_added in c++

JAVA/BasicProblems/Calculator.java
A simple calculator program using switch cases
=> Created Calculator.java

Java Programs
Java Program to check a string is palindrome or not
=> Palindrome String

JAVA/BasicProblems/HelloWorld.java
Added java program for hello world
closes #45
=> java hello world program added

Python/Check_Anagram.py
This pull request solves issue #74
=> Added Check_anagram_code

Python/rock_paper_scissors.py
Added rock paper scissors game to :- /hactoberfest_contribution_2022/Python/
=> Rock paper scissors game

Python/Python_all_important_patterns_in_one_file.py
This file contains almost all important patterns in python. I will add more with time
=> Python all important patterns 

Java_Swap_Two_Nos
Write a program in Java to swap two numbers(using a third variable).
=> Swap Two Numbers

JAVA/BasicProblems/Kadane's Algorithm.java
I have added a solution . Please review and merge the PR.
=> Added Kadane's Algo on java

Python/OOP/Readme.md, Python/OOP/athlete/Athlete.py, Python/OOP/basketball_player/Basketball_player.py, Python/OOP/main/Main.py, Python/OOP/soccer_player/Soccer_player.py, Typescript/product_management_system/.gitignore, Typescript/product_management_system/Readme.md, Typescript/product_management_system/package.json, Typescript/product_management_system/src/index.ts, Typescript/product_management_system/src/interface/IWarehouse.ts, Typescript/product_management_system/src/interface/Product.ts, Typescript/product_management_system/src/models/Company.ts, Typescript/product_management_system/src/models/Warehouse.ts, Typescript/product_management_system/src/service/CompanyService.ts, Typescript/product_management_system/src/service/WarehouseService.ts, Typescript/product_management_system/src/service/gateway/ICompanyService.ts, Typescript/product_management_system/src/service/gateway/IWarehouseService.ts, Typescript/product_management_system/src/utils/ProductFactory.ts, Typescript/product_management_system/tsconfig.json
Hi there 👋, my name is Juan Pablo, I'm from Colombia and I wanted to start contributing with this repo as my first time doing this, what I did is basically a little project using object oriented programming in python, hope you like it. 
Greetings!
=> Feature: OOP BMI athlete calculator project development

C++/Linked Lists/Append.cpp, C++/Linked Lists/Delete_Node.cpp, C++/Linked Lists/EliminateDuplicates.cpp, C++/Linked Lists/Find_a_node.cpp, C++/Linked Lists/Insert_recursive.cpp, C++/Linked Lists/Length_of_LL.cpp, C++/Linked Lists/Length_recursive.cpp, C++/Linked Lists/Linekedlist.cpp, C++/Linked Lists/Node.cpp, C++/Linked Lists/Print_ith_node.cpp, C++/Linked Lists/Take_Input.cpp, C++/Linked Lists/reverse.cpp
It would be really nice if I could be given the opportunity to contribute, as these 12 questions really form the base of working with Linked Lists.
=> Added Linked List Folder and added 12 new solved questions to it

Weather/contributors.md, Weather/style.css
Added hover effect to the card of weather app, so that when user takes cursor on it it will appear slightly different ,hope you will find it little helpful.
=> Hovereffect

C++/Negative cycle detection using Floyd Warshall Algorithm
Negative cycle detection in a graph using Floyd Warshall Algorithm.
=> Negative cycle detection using Floyd Warshall Algorithm

Python/Python Program to Extract Extension From the File Name.py
Hello @Sachindrck here is the submission for recently assigned issue.
I tried explaining what my code does using comments.
Please mention anything that needs to be changed.
=> Added Python Program to Extract Extension From the File Name

Python/oddEven.py
please accept the assigned task
=> factors of a given number

Python/ludo_game.py
First Player to reach the Exact Score wins
=> Ludo_Game in Python Added

Python/area_different_shapes.py
Added area calculator for different geometrical shapes
=> Added "area_different_shapes.py"

C++/Arrays/merge_sort.cpp
I have added the code of merge sort in C++. Please accept it @Sachindrck
=> merge sort added

C++/Power_of_2.cpp
This code checks weather the given number is a **power of 2** or not _without using any loop or recursion_.
=> Power_of_2.cpp

C++/Amount_in_Words.cpp
This is a C++ program that converts an amount (_in integer, upto 999999_) into words. 
[i/p –**231504**, output –**2 lakh 31 thousand 5 hundred and four only**]
=> Amount_in_Words.cpp

C++/towerOfHanoi.cpp
I added the program for tower of hanoi in C++.
=> Tower of Hanoi

JAVA/BasicProblems/Pascal'sTriangle.java
I have created Pascal's Triangle using java.
In Pascal's Triangle, each new number lies between two numbers and below them, and its value is the sum of the two numbers above it.
Please accept my PR ;)
=> Created Pascal's Triangle using Java

JAVA/Tic_Tac_Toe_with_Computer.java
This is a java program that serves as a **tic-tac-toe game** _between user and computer_. Here user just need to enter the coordinates of the place where-ever he/she wishes to put his/her mark. Computer automatically takes its turn and the game goes on.
_Please don't forget to change the class name from **Main** if it throws error._
=> Tic_Tac_Toe_with_Computer.java

C++/0-1Knapsack.cpp
Successfully completed program for 0-1knapsack problem . Please have a look and merge my contribution .
Thankyou!
=> 0 1 Knapsack problem in C++ (issue 129)

JAVA/WordCount.java
=> Count words from a string in java

C++/Recursion/Factorial_recursion.cpp
**Recursion** folder (_containing a simple program of computing factorial of a number using recursion_) has been added to the **C++ section.**
=> Added Recursion folder to C++ section.

C++/Arrays/Reverse_array.cpp
I have added a Program to reverse an array.
Please, merge it by giving "hacktoberfest-accepted" label.
=> Reverse_array.cpp

C++/Arrays/productofArray_exceptSelf.cpp
Hi,I added code for product of array except self in c++.
=> added product of array except self in c++

Python/Couting_characters.py
Python program to count the uppercase, lowercase, special characters, and numeric values
=> Counting_characters.py

C++/Pivot_number.cpp
=> created pivot_number

C++/Arrays/largest_row_sum.cpp
This program finds the greatest row sum and the row index in NxN matrix.
=> added a program to find the greatest row sum.

JavaScript/productsCrud/.gitignore, JavaScript/productsCrud/Readme.md, JavaScript/productsCrud/package.json, JavaScript/productsCrud/src/html/index.html, JavaScript/productsCrud/src/models/product.js, JavaScript/productsCrud/src/routes/product.routes.js, JavaScript/productsCrud/src/server.js
Hi there, I just created a mixed CRUD project using NodeJs and ExpressJS where you can interact with the DOM but also need to practice with any HTTP client like postman, insomnia or something like that.
Let me know what you think about. Thanks
=> Jp cano contribution

JAVA/Library.java
This is a java program that works similar to a library software.
**Here a user can:**
**1.** View the available books.
**2.** Add a book
**3.** Issue a book
**4.** Return a book
This helps in maintaining track of books in library.
_Please don't forget to change the class name from **Main** if it throws error._
=> Library.java

Python/finding_smallest_and_largest_word.py
@Sachindrck  Please verify it #161
=> Added a python program to find smallest and largest word in given string

Java-DSA/Branch and Bound/TSP.java
In Java DSA folder - added a new folder Branch and Bound and solved the Travelling Salesperson Algorithm.
Fixes: #227
=> added Travelling Salesperson Problem in new Branch and Bound folder

C++/Stacks/implementing_stack_operations.cpp
hi ,I added code for stack operations in c++.
=> Added Stack operations in c++

C++/Binary-Searchh-Tree.cpp
Hey there! I have added bst code in cpp to the c++ folder. Hope you would accept it!
=> added bst code in cpp

Python/hcf_gcd.py
https://github.com/Sachindrck/hactoberfest_contribution_2022/issues/16
=> Python Program to Find HCF or GCD

Java-DSA/Stacks/Arraystack.java, Java-DSA/Stacks/Stack.java
it is the code for implementing array stacks in javaa
=> array stack in java

JAVA/Exceution_complex_number_operation.java, JAVA/complex.java
One file contains function while another file contains execution of those function
=> Complex number operation

C++/Arrays/insertion_sort.cpp
=> sort an array using insertion sort

JAVA/BasicProblems/InsertionSort.java
I added an algorithm to Java folder
#Hacktoberfest2022
=> Added an algorithm

C++/Longest Increasing Subsequence.cpp
I have added Longest Increasing Subsequence problem of dynamic programming in CPP,
=> Longest Increasing Subsequence problem, hacktoberfest2022

handtracker
=> machine learning project

Difference_Between_Even_and_Odd.cpp
Solved the issue for Difference between sums of odd and even digits #270
=> Added solution for Difference_Between_Even_and_Odd
